# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/vins/Projects/cpp/ys_proto3/ys_proto

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/vins/Projects/cpp/ys_proto3/ys_proto

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vins/Projects/cpp/ys_proto3/ys_proto/CMakeFiles /home/vins/Projects/cpp/ys_proto3/ys_proto/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vins/Projects/cpp/ys_proto3/ys_proto/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ys_proto

# Build rule for target.
ys_proto: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ys_proto
.PHONY : ys_proto

# fast build rule for target.
ys_proto/fast:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/build
.PHONY : ys_proto/fast

src/apps/activity_message.o: src/apps/activity_message.cpp.o
.PHONY : src/apps/activity_message.o

# target to build an object file
src/apps/activity_message.cpp.o:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/apps/activity_message.cpp.o
.PHONY : src/apps/activity_message.cpp.o

src/apps/activity_message.i: src/apps/activity_message.cpp.i
.PHONY : src/apps/activity_message.i

# target to preprocess a source file
src/apps/activity_message.cpp.i:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/apps/activity_message.cpp.i
.PHONY : src/apps/activity_message.cpp.i

src/apps/activity_message.s: src/apps/activity_message.cpp.s
.PHONY : src/apps/activity_message.s

# target to generate assembly for a file
src/apps/activity_message.cpp.s:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/apps/activity_message.cpp.s
.PHONY : src/apps/activity_message.cpp.s

src/apps/apps.o: src/apps/apps.cpp.o
.PHONY : src/apps/apps.o

# target to build an object file
src/apps/apps.cpp.o:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/apps/apps.cpp.o
.PHONY : src/apps/apps.cpp.o

src/apps/apps.i: src/apps/apps.cpp.i
.PHONY : src/apps/apps.i

# target to preprocess a source file
src/apps/apps.cpp.i:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/apps/apps.cpp.i
.PHONY : src/apps/apps.cpp.i

src/apps/apps.s: src/apps/apps.cpp.s
.PHONY : src/apps/apps.s

# target to generate assembly for a file
src/apps/apps.cpp.s:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/apps/apps.cpp.s
.PHONY : src/apps/apps.cpp.s

src/apps/ysclient.o: src/apps/ysclient.cpp.o
.PHONY : src/apps/ysclient.o

# target to build an object file
src/apps/ysclient.cpp.o:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/apps/ysclient.cpp.o
.PHONY : src/apps/ysclient.cpp.o

src/apps/ysclient.i: src/apps/ysclient.cpp.i
.PHONY : src/apps/ysclient.i

# target to preprocess a source file
src/apps/ysclient.cpp.i:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/apps/ysclient.cpp.i
.PHONY : src/apps/ysclient.cpp.i

src/apps/ysclient.s: src/apps/ysclient.cpp.s
.PHONY : src/apps/ysclient.s

# target to generate assembly for a file
src/apps/ysclient.cpp.s:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/apps/ysclient.cpp.s
.PHONY : src/apps/ysclient.cpp.s

src/apps/ysclientActions.o: src/apps/ysclientActions.cpp.o
.PHONY : src/apps/ysclientActions.o

# target to build an object file
src/apps/ysclientActions.cpp.o:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/apps/ysclientActions.cpp.o
.PHONY : src/apps/ysclientActions.cpp.o

src/apps/ysclientActions.i: src/apps/ysclientActions.cpp.i
.PHONY : src/apps/ysclientActions.i

# target to preprocess a source file
src/apps/ysclientActions.cpp.i:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/apps/ysclientActions.cpp.i
.PHONY : src/apps/ysclientActions.cpp.i

src/apps/ysclientActions.s: src/apps/ysclientActions.cpp.s
.PHONY : src/apps/ysclientActions.s

# target to generate assembly for a file
src/apps/ysclientActions.cpp.s:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/apps/ysclientActions.cpp.s
.PHONY : src/apps/ysclientActions.cpp.s

src/debug.o: src/debug.cpp.o
.PHONY : src/debug.o

# target to build an object file
src/debug.cpp.o:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/debug.cpp.o
.PHONY : src/debug.cpp.o

src/debug.i: src/debug.cpp.i
.PHONY : src/debug.i

# target to preprocess a source file
src/debug.cpp.i:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/debug.cpp.i
.PHONY : src/debug.cpp.i

src/debug.s: src/debug.cpp.s
.PHONY : src/debug.s

# target to generate assembly for a file
src/debug.cpp.s:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/debug.cpp.s
.PHONY : src/debug.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/output/xmlLog.o: src/output/xmlLog.cpp.o
.PHONY : src/output/xmlLog.o

# target to build an object file
src/output/xmlLog.cpp.o:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/output/xmlLog.cpp.o
.PHONY : src/output/xmlLog.cpp.o

src/output/xmlLog.i: src/output/xmlLog.cpp.i
.PHONY : src/output/xmlLog.i

# target to preprocess a source file
src/output/xmlLog.cpp.i:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/output/xmlLog.cpp.i
.PHONY : src/output/xmlLog.cpp.i

src/output/xmlLog.s: src/output/xmlLog.cpp.s
.PHONY : src/output/xmlLog.s

# target to generate assembly for a file
src/output/xmlLog.cpp.s:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/output/xmlLog.cpp.s
.PHONY : src/output/xmlLog.cpp.s

src/serialization/ackowledge.o: src/serialization/ackowledge.cpp.o
.PHONY : src/serialization/ackowledge.o

# target to build an object file
src/serialization/ackowledge.cpp.o:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/serialization/ackowledge.cpp.o
.PHONY : src/serialization/ackowledge.cpp.o

src/serialization/ackowledge.i: src/serialization/ackowledge.cpp.i
.PHONY : src/serialization/ackowledge.i

# target to preprocess a source file
src/serialization/ackowledge.cpp.i:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/serialization/ackowledge.cpp.i
.PHONY : src/serialization/ackowledge.cpp.i

src/serialization/ackowledge.s: src/serialization/ackowledge.cpp.s
.PHONY : src/serialization/ackowledge.s

# target to generate assembly for a file
src/serialization/ackowledge.cpp.s:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/serialization/ackowledge.cpp.s
.PHONY : src/serialization/ackowledge.cpp.s

src/serialization/airDisplayOpt.o: src/serialization/airDisplayOpt.cpp.o
.PHONY : src/serialization/airDisplayOpt.o

# target to build an object file
src/serialization/airDisplayOpt.cpp.o:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/serialization/airDisplayOpt.cpp.o
.PHONY : src/serialization/airDisplayOpt.cpp.o

src/serialization/airDisplayOpt.i: src/serialization/airDisplayOpt.cpp.i
.PHONY : src/serialization/airDisplayOpt.i

# target to preprocess a source file
src/serialization/airDisplayOpt.cpp.i:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/serialization/airDisplayOpt.cpp.i
.PHONY : src/serialization/airDisplayOpt.cpp.i

src/serialization/airDisplayOpt.s: src/serialization/airDisplayOpt.cpp.s
.PHONY : src/serialization/airDisplayOpt.s

# target to generate assembly for a file
src/serialization/airDisplayOpt.cpp.s:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/serialization/airDisplayOpt.cpp.s
.PHONY : src/serialization/airDisplayOpt.cpp.s

src/serialization/airList.o: src/serialization/airList.cpp.o
.PHONY : src/serialization/airList.o

# target to build an object file
src/serialization/airList.cpp.o:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/serialization/airList.cpp.o
.PHONY : src/serialization/airList.cpp.o

src/serialization/airList.i: src/serialization/airList.cpp.i
.PHONY : src/serialization/airList.i

# target to preprocess a source file
src/serialization/airList.cpp.i:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/serialization/airList.cpp.i
.PHONY : src/serialization/airList.cpp.i

src/serialization/airList.s: src/serialization/airList.cpp.s
.PHONY : src/serialization/airList.s

# target to generate assembly for a file
src/serialization/airList.cpp.s:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/serialization/airList.cpp.s
.PHONY : src/serialization/airList.cpp.s

src/serialization/damage.o: src/serialization/damage.cpp.o
.PHONY : src/serialization/damage.o

# target to build an object file
src/serialization/damage.cpp.o:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/serialization/damage.cpp.o
.PHONY : src/serialization/damage.cpp.o

src/serialization/damage.i: src/serialization/damage.cpp.i
.PHONY : src/serialization/damage.i

# target to preprocess a source file
src/serialization/damage.cpp.i:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/serialization/damage.cpp.i
.PHONY : src/serialization/damage.cpp.i

src/serialization/damage.s: src/serialization/damage.cpp.s
.PHONY : src/serialization/damage.s

# target to generate assembly for a file
src/serialization/damage.cpp.s:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/serialization/damage.cpp.s
.PHONY : src/serialization/damage.cpp.s

src/serialization/endianess.o: src/serialization/endianess.cpp.o
.PHONY : src/serialization/endianess.o

# target to build an object file
src/serialization/endianess.cpp.o:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/serialization/endianess.cpp.o
.PHONY : src/serialization/endianess.cpp.o

src/serialization/endianess.i: src/serialization/endianess.cpp.i
.PHONY : src/serialization/endianess.i

# target to preprocess a source file
src/serialization/endianess.cpp.i:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/serialization/endianess.cpp.i
.PHONY : src/serialization/endianess.cpp.i

src/serialization/endianess.s: src/serialization/endianess.cpp.s
.PHONY : src/serialization/endianess.s

# target to generate assembly for a file
src/serialization/endianess.cpp.s:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/serialization/endianess.cpp.s
.PHONY : src/serialization/endianess.cpp.s

src/serialization/flight.o: src/serialization/flight.cpp.o
.PHONY : src/serialization/flight.o

# target to build an object file
src/serialization/flight.cpp.o:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/serialization/flight.cpp.o
.PHONY : src/serialization/flight.cpp.o

src/serialization/flight.i: src/serialization/flight.cpp.i
.PHONY : src/serialization/flight.i

# target to preprocess a source file
src/serialization/flight.cpp.i:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/serialization/flight.cpp.i
.PHONY : src/serialization/flight.cpp.i

src/serialization/flight.s: src/serialization/flight.cpp.s
.PHONY : src/serialization/flight.s

# target to generate assembly for a file
src/serialization/flight.cpp.s:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/serialization/flight.cpp.s
.PHONY : src/serialization/flight.cpp.s

src/serialization/ground.o: src/serialization/ground.cpp.o
.PHONY : src/serialization/ground.o

# target to build an object file
src/serialization/ground.cpp.o:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/serialization/ground.cpp.o
.PHONY : src/serialization/ground.cpp.o

src/serialization/ground.i: src/serialization/ground.cpp.i
.PHONY : src/serialization/ground.i

# target to preprocess a source file
src/serialization/ground.cpp.i:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/serialization/ground.cpp.i
.PHONY : src/serialization/ground.cpp.i

src/serialization/ground.s: src/serialization/ground.cpp.s
.PHONY : src/serialization/ground.s

# target to generate assembly for a file
src/serialization/ground.cpp.s:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/serialization/ground.cpp.s
.PHONY : src/serialization/ground.cpp.s

src/serialization/header.o: src/serialization/header.cpp.o
.PHONY : src/serialization/header.o

# target to build an object file
src/serialization/header.cpp.o:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/serialization/header.cpp.o
.PHONY : src/serialization/header.cpp.o

src/serialization/header.i: src/serialization/header.cpp.i
.PHONY : src/serialization/header.i

# target to preprocess a source file
src/serialization/header.cpp.i:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/serialization/header.cpp.i
.PHONY : src/serialization/header.cpp.i

src/serialization/header.s: src/serialization/header.cpp.s
.PHONY : src/serialization/header.s

# target to generate assembly for a file
src/serialization/header.cpp.s:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/serialization/header.cpp.s
.PHONY : src/serialization/header.cpp.s

src/serialization/includeAll.o: src/serialization/includeAll.cpp.o
.PHONY : src/serialization/includeAll.o

# target to build an object file
src/serialization/includeAll.cpp.o:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/serialization/includeAll.cpp.o
.PHONY : src/serialization/includeAll.cpp.o

src/serialization/includeAll.i: src/serialization/includeAll.cpp.i
.PHONY : src/serialization/includeAll.i

# target to preprocess a source file
src/serialization/includeAll.cpp.i:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/serialization/includeAll.cpp.i
.PHONY : src/serialization/includeAll.cpp.i

src/serialization/includeAll.s: src/serialization/includeAll.cpp.s
.PHONY : src/serialization/includeAll.s

# target to generate assembly for a file
src/serialization/includeAll.cpp.s:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/serialization/includeAll.cpp.s
.PHONY : src/serialization/includeAll.cpp.s

src/serialization/int.o: src/serialization/int.cpp.o
.PHONY : src/serialization/int.o

# target to build an object file
src/serialization/int.cpp.o:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/serialization/int.cpp.o
.PHONY : src/serialization/int.cpp.o

src/serialization/int.i: src/serialization/int.cpp.i
.PHONY : src/serialization/int.i

# target to preprocess a source file
src/serialization/int.cpp.i:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/serialization/int.cpp.i
.PHONY : src/serialization/int.cpp.i

src/serialization/int.s: src/serialization/int.cpp.s
.PHONY : src/serialization/int.s

# target to generate assembly for a file
src/serialization/int.cpp.s:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/serialization/int.cpp.s
.PHONY : src/serialization/int.cpp.s

src/serialization/left.o: src/serialization/left.cpp.o
.PHONY : src/serialization/left.o

# target to build an object file
src/serialization/left.cpp.o:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/serialization/left.cpp.o
.PHONY : src/serialization/left.cpp.o

src/serialization/left.i: src/serialization/left.cpp.i
.PHONY : src/serialization/left.i

# target to preprocess a source file
src/serialization/left.cpp.i:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/serialization/left.cpp.i
.PHONY : src/serialization/left.cpp.i

src/serialization/left.s: src/serialization/left.cpp.s
.PHONY : src/serialization/left.s

# target to generate assembly for a file
src/serialization/left.cpp.s:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/serialization/left.cpp.s
.PHONY : src/serialization/left.cpp.s

src/serialization/login.o: src/serialization/login.cpp.o
.PHONY : src/serialization/login.o

# target to build an object file
src/serialization/login.cpp.o:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/serialization/login.cpp.o
.PHONY : src/serialization/login.cpp.o

src/serialization/login.i: src/serialization/login.cpp.i
.PHONY : src/serialization/login.i

# target to preprocess a source file
src/serialization/login.cpp.i:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/serialization/login.cpp.i
.PHONY : src/serialization/login.cpp.i

src/serialization/login.s: src/serialization/login.cpp.s
.PHONY : src/serialization/login.s

# target to generate assembly for a file
src/serialization/login.cpp.s:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/serialization/login.cpp.s
.PHONY : src/serialization/login.cpp.s

src/serialization/map.o: src/serialization/map.cpp.o
.PHONY : src/serialization/map.o

# target to build an object file
src/serialization/map.cpp.o:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/serialization/map.cpp.o
.PHONY : src/serialization/map.cpp.o

src/serialization/map.i: src/serialization/map.cpp.i
.PHONY : src/serialization/map.i

# target to preprocess a source file
src/serialization/map.cpp.i:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/serialization/map.cpp.i
.PHONY : src/serialization/map.cpp.i

src/serialization/map.s: src/serialization/map.cpp.s
.PHONY : src/serialization/map.s

# target to generate assembly for a file
src/serialization/map.cpp.s:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/serialization/map.cpp.s
.PHONY : src/serialization/map.cpp.s

src/serialization/message.o: src/serialization/message.cpp.o
.PHONY : src/serialization/message.o

# target to build an object file
src/serialization/message.cpp.o:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/serialization/message.cpp.o
.PHONY : src/serialization/message.cpp.o

src/serialization/message.i: src/serialization/message.cpp.i
.PHONY : src/serialization/message.i

# target to preprocess a source file
src/serialization/message.cpp.i:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/serialization/message.cpp.i
.PHONY : src/serialization/message.cpp.i

src/serialization/message.s: src/serialization/message.cpp.s
.PHONY : src/serialization/message.s

# target to generate assembly for a file
src/serialization/message.cpp.s:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/serialization/message.cpp.s
.PHONY : src/serialization/message.cpp.s

src/serialization/missileOpt.o: src/serialization/missileOpt.cpp.o
.PHONY : src/serialization/missileOpt.o

# target to build an object file
src/serialization/missileOpt.cpp.o:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/serialization/missileOpt.cpp.o
.PHONY : src/serialization/missileOpt.cpp.o

src/serialization/missileOpt.i: src/serialization/missileOpt.cpp.i
.PHONY : src/serialization/missileOpt.i

# target to preprocess a source file
src/serialization/missileOpt.cpp.i:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/serialization/missileOpt.cpp.i
.PHONY : src/serialization/missileOpt.cpp.i

src/serialization/missileOpt.s: src/serialization/missileOpt.cpp.s
.PHONY : src/serialization/missileOpt.s

# target to generate assembly for a file
src/serialization/missileOpt.cpp.s:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/serialization/missileOpt.cpp.s
.PHONY : src/serialization/missileOpt.cpp.s

src/serialization/unpack.o: src/serialization/unpack.cpp.o
.PHONY : src/serialization/unpack.o

# target to build an object file
src/serialization/unpack.cpp.o:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/serialization/unpack.cpp.o
.PHONY : src/serialization/unpack.cpp.o

src/serialization/unpack.i: src/serialization/unpack.cpp.i
.PHONY : src/serialization/unpack.i

# target to preprocess a source file
src/serialization/unpack.cpp.i:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/serialization/unpack.cpp.i
.PHONY : src/serialization/unpack.cpp.i

src/serialization/unpack.s: src/serialization/unpack.cpp.s
.PHONY : src/serialization/unpack.s

# target to generate assembly for a file
src/serialization/unpack.cpp.s:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/serialization/unpack.cpp.s
.PHONY : src/serialization/unpack.cpp.s

src/serialization/userlist.o: src/serialization/userlist.cpp.o
.PHONY : src/serialization/userlist.o

# target to build an object file
src/serialization/userlist.cpp.o:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/serialization/userlist.cpp.o
.PHONY : src/serialization/userlist.cpp.o

src/serialization/userlist.i: src/serialization/userlist.cpp.i
.PHONY : src/serialization/userlist.i

# target to preprocess a source file
src/serialization/userlist.cpp.i:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/serialization/userlist.cpp.i
.PHONY : src/serialization/userlist.cpp.i

src/serialization/userlist.s: src/serialization/userlist.cpp.s
.PHONY : src/serialization/userlist.s

# target to generate assembly for a file
src/serialization/userlist.cpp.s:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/serialization/userlist.cpp.s
.PHONY : src/serialization/userlist.cpp.s

src/serialization/weather.o: src/serialization/weather.cpp.o
.PHONY : src/serialization/weather.o

# target to build an object file
src/serialization/weather.cpp.o:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/serialization/weather.cpp.o
.PHONY : src/serialization/weather.cpp.o

src/serialization/weather.i: src/serialization/weather.cpp.i
.PHONY : src/serialization/weather.i

# target to preprocess a source file
src/serialization/weather.cpp.i:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/serialization/weather.cpp.i
.PHONY : src/serialization/weather.cpp.i

src/serialization/weather.s: src/serialization/weather.cpp.s
.PHONY : src/serialization/weather.s

# target to generate assembly for a file
src/serialization/weather.cpp.s:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/serialization/weather.cpp.s
.PHONY : src/serialization/weather.cpp.s

src/sockets/linux.o: src/sockets/linux.cpp.o
.PHONY : src/sockets/linux.o

# target to build an object file
src/sockets/linux.cpp.o:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/sockets/linux.cpp.o
.PHONY : src/sockets/linux.cpp.o

src/sockets/linux.i: src/sockets/linux.cpp.i
.PHONY : src/sockets/linux.i

# target to preprocess a source file
src/sockets/linux.cpp.i:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/sockets/linux.cpp.i
.PHONY : src/sockets/linux.cpp.i

src/sockets/linux.s: src/sockets/linux.cpp.s
.PHONY : src/sockets/linux.s

# target to generate assembly for a file
src/sockets/linux.cpp.s:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/sockets/linux.cpp.s
.PHONY : src/sockets/linux.cpp.s

src/sockets/socketYS.o: src/sockets/socketYS.cpp.o
.PHONY : src/sockets/socketYS.o

# target to build an object file
src/sockets/socketYS.cpp.o:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/sockets/socketYS.cpp.o
.PHONY : src/sockets/socketYS.cpp.o

src/sockets/socketYS.i: src/sockets/socketYS.cpp.i
.PHONY : src/sockets/socketYS.i

# target to preprocess a source file
src/sockets/socketYS.cpp.i:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/sockets/socketYS.cpp.i
.PHONY : src/sockets/socketYS.cpp.i

src/sockets/socketYS.s: src/sockets/socketYS.cpp.s
.PHONY : src/sockets/socketYS.s

# target to generate assembly for a file
src/sockets/socketYS.cpp.s:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/sockets/socketYS.cpp.s
.PHONY : src/sockets/socketYS.cpp.s

src/sockets/windows.o: src/sockets/windows.cpp.o
.PHONY : src/sockets/windows.o

# target to build an object file
src/sockets/windows.cpp.o:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/sockets/windows.cpp.o
.PHONY : src/sockets/windows.cpp.o

src/sockets/windows.i: src/sockets/windows.cpp.i
.PHONY : src/sockets/windows.i

# target to preprocess a source file
src/sockets/windows.cpp.i:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/sockets/windows.cpp.i
.PHONY : src/sockets/windows.cpp.i

src/sockets/windows.s: src/sockets/windows.cpp.s
.PHONY : src/sockets/windows.s

# target to generate assembly for a file
src/sockets/windows.cpp.s:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/sockets/windows.cpp.s
.PHONY : src/sockets/windows.cpp.s

src/stringarray.o: src/stringarray.cpp.o
.PHONY : src/stringarray.o

# target to build an object file
src/stringarray.cpp.o:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/stringarray.cpp.o
.PHONY : src/stringarray.cpp.o

src/stringarray.i: src/stringarray.cpp.i
.PHONY : src/stringarray.i

# target to preprocess a source file
src/stringarray.cpp.i:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/stringarray.cpp.i
.PHONY : src/stringarray.cpp.i

src/stringarray.s: src/stringarray.cpp.s
.PHONY : src/stringarray.s

# target to generate assembly for a file
src/stringarray.cpp.s:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/stringarray.cpp.s
.PHONY : src/stringarray.cpp.s

src/test.o: src/test.cpp.o
.PHONY : src/test.o

# target to build an object file
src/test.cpp.o:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/test.cpp.o
.PHONY : src/test.cpp.o

src/test.i: src/test.cpp.i
.PHONY : src/test.i

# target to preprocess a source file
src/test.cpp.i:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/test.cpp.i
.PHONY : src/test.cpp.i

src/test.s: src/test.cpp.s
.PHONY : src/test.s

# target to generate assembly for a file
src/test.cpp.s:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/test.cpp.s
.PHONY : src/test.cpp.s

src/tests.o: src/tests.cpp.o
.PHONY : src/tests.o

# target to build an object file
src/tests.cpp.o:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/tests.cpp.o
.PHONY : src/tests.cpp.o

src/tests.i: src/tests.cpp.i
.PHONY : src/tests.i

# target to preprocess a source file
src/tests.cpp.i:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/tests.cpp.i
.PHONY : src/tests.cpp.i

src/tests.s: src/tests.cpp.s
.PHONY : src/tests.s

# target to generate assembly for a file
src/tests.cpp.s:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/tests.cpp.s
.PHONY : src/tests.cpp.s

src/types/stringarray.o: src/types/stringarray.cpp.o
.PHONY : src/types/stringarray.o

# target to build an object file
src/types/stringarray.cpp.o:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/types/stringarray.cpp.o
.PHONY : src/types/stringarray.cpp.o

src/types/stringarray.i: src/types/stringarray.cpp.i
.PHONY : src/types/stringarray.i

# target to preprocess a source file
src/types/stringarray.cpp.i:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/types/stringarray.cpp.i
.PHONY : src/types/stringarray.cpp.i

src/types/stringarray.s: src/types/stringarray.cpp.s
.PHONY : src/types/stringarray.s

# target to generate assembly for a file
src/types/stringarray.cpp.s:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/types/stringarray.cpp.s
.PHONY : src/types/stringarray.cpp.s

src/types/ys/airList.o: src/types/ys/airList.cpp.o
.PHONY : src/types/ys/airList.o

# target to build an object file
src/types/ys/airList.cpp.o:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/types/ys/airList.cpp.o
.PHONY : src/types/ys/airList.cpp.o

src/types/ys/airList.i: src/types/ys/airList.cpp.i
.PHONY : src/types/ys/airList.i

# target to preprocess a source file
src/types/ys/airList.cpp.i:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/types/ys/airList.cpp.i
.PHONY : src/types/ys/airList.cpp.i

src/types/ys/airList.s: src/types/ys/airList.cpp.s
.PHONY : src/types/ys/airList.s

# target to generate assembly for a file
src/types/ys/airList.cpp.s:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/types/ys/airList.cpp.s
.PHONY : src/types/ys/airList.cpp.s

src/types/ys/includeAll.o: src/types/ys/includeAll.cpp.o
.PHONY : src/types/ys/includeAll.o

# target to build an object file
src/types/ys/includeAll.cpp.o:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/types/ys/includeAll.cpp.o
.PHONY : src/types/ys/includeAll.cpp.o

src/types/ys/includeAll.i: src/types/ys/includeAll.cpp.i
.PHONY : src/types/ys/includeAll.i

# target to preprocess a source file
src/types/ys/includeAll.cpp.i:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/types/ys/includeAll.cpp.i
.PHONY : src/types/ys/includeAll.cpp.i

src/types/ys/includeAll.s: src/types/ys/includeAll.cpp.s
.PHONY : src/types/ys/includeAll.s

# target to generate assembly for a file
src/types/ys/includeAll.cpp.s:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/types/ys/includeAll.cpp.s
.PHONY : src/types/ys/includeAll.cpp.s

src/types/ys/login.o: src/types/ys/login.cpp.o
.PHONY : src/types/ys/login.o

# target to build an object file
src/types/ys/login.cpp.o:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/types/ys/login.cpp.o
.PHONY : src/types/ys/login.cpp.o

src/types/ys/login.i: src/types/ys/login.cpp.i
.PHONY : src/types/ys/login.i

# target to preprocess a source file
src/types/ys/login.cpp.i:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/types/ys/login.cpp.i
.PHONY : src/types/ys/login.cpp.i

src/types/ys/login.s: src/types/ys/login.cpp.s
.PHONY : src/types/ys/login.s

# target to generate assembly for a file
src/types/ys/login.cpp.s:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/types/ys/login.cpp.s
.PHONY : src/types/ys/login.cpp.s

src/types/ys/map.o: src/types/ys/map.cpp.o
.PHONY : src/types/ys/map.o

# target to build an object file
src/types/ys/map.cpp.o:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/types/ys/map.cpp.o
.PHONY : src/types/ys/map.cpp.o

src/types/ys/map.i: src/types/ys/map.cpp.i
.PHONY : src/types/ys/map.i

# target to preprocess a source file
src/types/ys/map.cpp.i:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/types/ys/map.cpp.i
.PHONY : src/types/ys/map.cpp.i

src/types/ys/map.s: src/types/ys/map.cpp.s
.PHONY : src/types/ys/map.s

# target to generate assembly for a file
src/types/ys/map.cpp.s:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/types/ys/map.cpp.s
.PHONY : src/types/ys/map.cpp.s

src/types/ys/missileOpt.o: src/types/ys/missileOpt.cpp.o
.PHONY : src/types/ys/missileOpt.o

# target to build an object file
src/types/ys/missileOpt.cpp.o:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/types/ys/missileOpt.cpp.o
.PHONY : src/types/ys/missileOpt.cpp.o

src/types/ys/missileOpt.i: src/types/ys/missileOpt.cpp.i
.PHONY : src/types/ys/missileOpt.i

# target to preprocess a source file
src/types/ys/missileOpt.cpp.i:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/types/ys/missileOpt.cpp.i
.PHONY : src/types/ys/missileOpt.cpp.i

src/types/ys/missileOpt.s: src/types/ys/missileOpt.cpp.s
.PHONY : src/types/ys/missileOpt.s

# target to generate assembly for a file
src/types/ys/missileOpt.cpp.s:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/types/ys/missileOpt.cpp.s
.PHONY : src/types/ys/missileOpt.cpp.s

src/types/ys/tacknowledge.o: src/types/ys/tacknowledge.cpp.o
.PHONY : src/types/ys/tacknowledge.o

# target to build an object file
src/types/ys/tacknowledge.cpp.o:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/types/ys/tacknowledge.cpp.o
.PHONY : src/types/ys/tacknowledge.cpp.o

src/types/ys/tacknowledge.i: src/types/ys/tacknowledge.cpp.i
.PHONY : src/types/ys/tacknowledge.i

# target to preprocess a source file
src/types/ys/tacknowledge.cpp.i:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/types/ys/tacknowledge.cpp.i
.PHONY : src/types/ys/tacknowledge.cpp.i

src/types/ys/tacknowledge.s: src/types/ys/tacknowledge.cpp.s
.PHONY : src/types/ys/tacknowledge.s

# target to generate assembly for a file
src/types/ys/tacknowledge.cpp.s:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/types/ys/tacknowledge.cpp.s
.PHONY : src/types/ys/tacknowledge.cpp.s

src/types/ys/tairDisplayOpt.o: src/types/ys/tairDisplayOpt.cpp.o
.PHONY : src/types/ys/tairDisplayOpt.o

# target to build an object file
src/types/ys/tairDisplayOpt.cpp.o:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/types/ys/tairDisplayOpt.cpp.o
.PHONY : src/types/ys/tairDisplayOpt.cpp.o

src/types/ys/tairDisplayOpt.i: src/types/ys/tairDisplayOpt.cpp.i
.PHONY : src/types/ys/tairDisplayOpt.i

# target to preprocess a source file
src/types/ys/tairDisplayOpt.cpp.i:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/types/ys/tairDisplayOpt.cpp.i
.PHONY : src/types/ys/tairDisplayOpt.cpp.i

src/types/ys/tairDisplayOpt.s: src/types/ys/tairDisplayOpt.cpp.s
.PHONY : src/types/ys/tairDisplayOpt.s

# target to generate assembly for a file
src/types/ys/tairDisplayOpt.cpp.s:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/types/ys/tairDisplayOpt.cpp.s
.PHONY : src/types/ys/tairDisplayOpt.cpp.s

src/types/ys/tairList.o: src/types/ys/tairList.cpp.o
.PHONY : src/types/ys/tairList.o

# target to build an object file
src/types/ys/tairList.cpp.o:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/types/ys/tairList.cpp.o
.PHONY : src/types/ys/tairList.cpp.o

src/types/ys/tairList.i: src/types/ys/tairList.cpp.i
.PHONY : src/types/ys/tairList.i

# target to preprocess a source file
src/types/ys/tairList.cpp.i:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/types/ys/tairList.cpp.i
.PHONY : src/types/ys/tairList.cpp.i

src/types/ys/tairList.s: src/types/ys/tairList.cpp.s
.PHONY : src/types/ys/tairList.s

# target to generate assembly for a file
src/types/ys/tairList.cpp.s:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/types/ys/tairList.cpp.s
.PHONY : src/types/ys/tairList.cpp.s

src/types/ys/tdamage.o: src/types/ys/tdamage.cpp.o
.PHONY : src/types/ys/tdamage.o

# target to build an object file
src/types/ys/tdamage.cpp.o:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/types/ys/tdamage.cpp.o
.PHONY : src/types/ys/tdamage.cpp.o

src/types/ys/tdamage.i: src/types/ys/tdamage.cpp.i
.PHONY : src/types/ys/tdamage.i

# target to preprocess a source file
src/types/ys/tdamage.cpp.i:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/types/ys/tdamage.cpp.i
.PHONY : src/types/ys/tdamage.cpp.i

src/types/ys/tdamage.s: src/types/ys/tdamage.cpp.s
.PHONY : src/types/ys/tdamage.s

# target to generate assembly for a file
src/types/ys/tdamage.cpp.s:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/types/ys/tdamage.cpp.s
.PHONY : src/types/ys/tdamage.cpp.s

src/types/ys/tflight.o: src/types/ys/tflight.cpp.o
.PHONY : src/types/ys/tflight.o

# target to build an object file
src/types/ys/tflight.cpp.o:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/types/ys/tflight.cpp.o
.PHONY : src/types/ys/tflight.cpp.o

src/types/ys/tflight.i: src/types/ys/tflight.cpp.i
.PHONY : src/types/ys/tflight.i

# target to preprocess a source file
src/types/ys/tflight.cpp.i:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/types/ys/tflight.cpp.i
.PHONY : src/types/ys/tflight.cpp.i

src/types/ys/tflight.s: src/types/ys/tflight.cpp.s
.PHONY : src/types/ys/tflight.s

# target to generate assembly for a file
src/types/ys/tflight.cpp.s:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/types/ys/tflight.cpp.s
.PHONY : src/types/ys/tflight.cpp.s

src/types/ys/tgound.o: src/types/ys/tgound.cpp.o
.PHONY : src/types/ys/tgound.o

# target to build an object file
src/types/ys/tgound.cpp.o:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/types/ys/tgound.cpp.o
.PHONY : src/types/ys/tgound.cpp.o

src/types/ys/tgound.i: src/types/ys/tgound.cpp.i
.PHONY : src/types/ys/tgound.i

# target to preprocess a source file
src/types/ys/tgound.cpp.i:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/types/ys/tgound.cpp.i
.PHONY : src/types/ys/tgound.cpp.i

src/types/ys/tgound.s: src/types/ys/tgound.cpp.s
.PHONY : src/types/ys/tgound.s

# target to generate assembly for a file
src/types/ys/tgound.cpp.s:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/types/ys/tgound.cpp.s
.PHONY : src/types/ys/tgound.cpp.s

src/types/ys/tground.o: src/types/ys/tground.cpp.o
.PHONY : src/types/ys/tground.o

# target to build an object file
src/types/ys/tground.cpp.o:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/types/ys/tground.cpp.o
.PHONY : src/types/ys/tground.cpp.o

src/types/ys/tground.i: src/types/ys/tground.cpp.i
.PHONY : src/types/ys/tground.i

# target to preprocess a source file
src/types/ys/tground.cpp.i:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/types/ys/tground.cpp.i
.PHONY : src/types/ys/tground.cpp.i

src/types/ys/tground.s: src/types/ys/tground.cpp.s
.PHONY : src/types/ys/tground.s

# target to generate assembly for a file
src/types/ys/tground.cpp.s:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/types/ys/tground.cpp.s
.PHONY : src/types/ys/tground.cpp.s

src/types/ys/theader.o: src/types/ys/theader.cpp.o
.PHONY : src/types/ys/theader.o

# target to build an object file
src/types/ys/theader.cpp.o:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/types/ys/theader.cpp.o
.PHONY : src/types/ys/theader.cpp.o

src/types/ys/theader.i: src/types/ys/theader.cpp.i
.PHONY : src/types/ys/theader.i

# target to preprocess a source file
src/types/ys/theader.cpp.i:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/types/ys/theader.cpp.i
.PHONY : src/types/ys/theader.cpp.i

src/types/ys/theader.s: src/types/ys/theader.cpp.s
.PHONY : src/types/ys/theader.s

# target to generate assembly for a file
src/types/ys/theader.cpp.s:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/types/ys/theader.cpp.s
.PHONY : src/types/ys/theader.cpp.s

src/types/ys/tint.o: src/types/ys/tint.cpp.o
.PHONY : src/types/ys/tint.o

# target to build an object file
src/types/ys/tint.cpp.o:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/types/ys/tint.cpp.o
.PHONY : src/types/ys/tint.cpp.o

src/types/ys/tint.i: src/types/ys/tint.cpp.i
.PHONY : src/types/ys/tint.i

# target to preprocess a source file
src/types/ys/tint.cpp.i:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/types/ys/tint.cpp.i
.PHONY : src/types/ys/tint.cpp.i

src/types/ys/tint.s: src/types/ys/tint.cpp.s
.PHONY : src/types/ys/tint.s

# target to generate assembly for a file
src/types/ys/tint.cpp.s:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/types/ys/tint.cpp.s
.PHONY : src/types/ys/tint.cpp.s

src/types/ys/tleft.o: src/types/ys/tleft.cpp.o
.PHONY : src/types/ys/tleft.o

# target to build an object file
src/types/ys/tleft.cpp.o:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/types/ys/tleft.cpp.o
.PHONY : src/types/ys/tleft.cpp.o

src/types/ys/tleft.i: src/types/ys/tleft.cpp.i
.PHONY : src/types/ys/tleft.i

# target to preprocess a source file
src/types/ys/tleft.cpp.i:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/types/ys/tleft.cpp.i
.PHONY : src/types/ys/tleft.cpp.i

src/types/ys/tleft.s: src/types/ys/tleft.cpp.s
.PHONY : src/types/ys/tleft.s

# target to generate assembly for a file
src/types/ys/tleft.cpp.s:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/types/ys/tleft.cpp.s
.PHONY : src/types/ys/tleft.cpp.s

src/types/ys/tlogin.o: src/types/ys/tlogin.cpp.o
.PHONY : src/types/ys/tlogin.o

# target to build an object file
src/types/ys/tlogin.cpp.o:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/types/ys/tlogin.cpp.o
.PHONY : src/types/ys/tlogin.cpp.o

src/types/ys/tlogin.i: src/types/ys/tlogin.cpp.i
.PHONY : src/types/ys/tlogin.i

# target to preprocess a source file
src/types/ys/tlogin.cpp.i:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/types/ys/tlogin.cpp.i
.PHONY : src/types/ys/tlogin.cpp.i

src/types/ys/tlogin.s: src/types/ys/tlogin.cpp.s
.PHONY : src/types/ys/tlogin.s

# target to generate assembly for a file
src/types/ys/tlogin.cpp.s:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/types/ys/tlogin.cpp.s
.PHONY : src/types/ys/tlogin.cpp.s

src/types/ys/tmap.o: src/types/ys/tmap.cpp.o
.PHONY : src/types/ys/tmap.o

# target to build an object file
src/types/ys/tmap.cpp.o:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/types/ys/tmap.cpp.o
.PHONY : src/types/ys/tmap.cpp.o

src/types/ys/tmap.i: src/types/ys/tmap.cpp.i
.PHONY : src/types/ys/tmap.i

# target to preprocess a source file
src/types/ys/tmap.cpp.i:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/types/ys/tmap.cpp.i
.PHONY : src/types/ys/tmap.cpp.i

src/types/ys/tmap.s: src/types/ys/tmap.cpp.s
.PHONY : src/types/ys/tmap.s

# target to generate assembly for a file
src/types/ys/tmap.cpp.s:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/types/ys/tmap.cpp.s
.PHONY : src/types/ys/tmap.cpp.s

src/types/ys/tmessage.o: src/types/ys/tmessage.cpp.o
.PHONY : src/types/ys/tmessage.o

# target to build an object file
src/types/ys/tmessage.cpp.o:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/types/ys/tmessage.cpp.o
.PHONY : src/types/ys/tmessage.cpp.o

src/types/ys/tmessage.i: src/types/ys/tmessage.cpp.i
.PHONY : src/types/ys/tmessage.i

# target to preprocess a source file
src/types/ys/tmessage.cpp.i:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/types/ys/tmessage.cpp.i
.PHONY : src/types/ys/tmessage.cpp.i

src/types/ys/tmessage.s: src/types/ys/tmessage.cpp.s
.PHONY : src/types/ys/tmessage.s

# target to generate assembly for a file
src/types/ys/tmessage.cpp.s:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/types/ys/tmessage.cpp.s
.PHONY : src/types/ys/tmessage.cpp.s

src/types/ys/tmissileOpt.o: src/types/ys/tmissileOpt.cpp.o
.PHONY : src/types/ys/tmissileOpt.o

# target to build an object file
src/types/ys/tmissileOpt.cpp.o:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/types/ys/tmissileOpt.cpp.o
.PHONY : src/types/ys/tmissileOpt.cpp.o

src/types/ys/tmissileOpt.i: src/types/ys/tmissileOpt.cpp.i
.PHONY : src/types/ys/tmissileOpt.i

# target to preprocess a source file
src/types/ys/tmissileOpt.cpp.i:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/types/ys/tmissileOpt.cpp.i
.PHONY : src/types/ys/tmissileOpt.cpp.i

src/types/ys/tmissileOpt.s: src/types/ys/tmissileOpt.cpp.s
.PHONY : src/types/ys/tmissileOpt.s

# target to generate assembly for a file
src/types/ys/tmissileOpt.cpp.s:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/types/ys/tmissileOpt.cpp.s
.PHONY : src/types/ys/tmissileOpt.cpp.s

src/types/ys/tuserlist.o: src/types/ys/tuserlist.cpp.o
.PHONY : src/types/ys/tuserlist.o

# target to build an object file
src/types/ys/tuserlist.cpp.o:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/types/ys/tuserlist.cpp.o
.PHONY : src/types/ys/tuserlist.cpp.o

src/types/ys/tuserlist.i: src/types/ys/tuserlist.cpp.i
.PHONY : src/types/ys/tuserlist.i

# target to preprocess a source file
src/types/ys/tuserlist.cpp.i:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/types/ys/tuserlist.cpp.i
.PHONY : src/types/ys/tuserlist.cpp.i

src/types/ys/tuserlist.s: src/types/ys/tuserlist.cpp.s
.PHONY : src/types/ys/tuserlist.s

# target to generate assembly for a file
src/types/ys/tuserlist.cpp.s:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/types/ys/tuserlist.cpp.s
.PHONY : src/types/ys/tuserlist.cpp.s

src/types/ys/tweather.o: src/types/ys/tweather.cpp.o
.PHONY : src/types/ys/tweather.o

# target to build an object file
src/types/ys/tweather.cpp.o:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/types/ys/tweather.cpp.o
.PHONY : src/types/ys/tweather.cpp.o

src/types/ys/tweather.i: src/types/ys/tweather.cpp.i
.PHONY : src/types/ys/tweather.i

# target to preprocess a source file
src/types/ys/tweather.cpp.i:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/types/ys/tweather.cpp.i
.PHONY : src/types/ys/tweather.cpp.i

src/types/ys/tweather.s: src/types/ys/tweather.cpp.s
.PHONY : src/types/ys/tweather.s

# target to generate assembly for a file
src/types/ys/tweather.cpp.s:
	$(MAKE) -f CMakeFiles/ys_proto.dir/build.make CMakeFiles/ys_proto.dir/src/types/ys/tweather.cpp.s
.PHONY : src/types/ys/tweather.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ys_proto"
	@echo "... src/apps/activity_message.o"
	@echo "... src/apps/activity_message.i"
	@echo "... src/apps/activity_message.s"
	@echo "... src/apps/apps.o"
	@echo "... src/apps/apps.i"
	@echo "... src/apps/apps.s"
	@echo "... src/apps/ysclient.o"
	@echo "... src/apps/ysclient.i"
	@echo "... src/apps/ysclient.s"
	@echo "... src/apps/ysclientActions.o"
	@echo "... src/apps/ysclientActions.i"
	@echo "... src/apps/ysclientActions.s"
	@echo "... src/debug.o"
	@echo "... src/debug.i"
	@echo "... src/debug.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/output/xmlLog.o"
	@echo "... src/output/xmlLog.i"
	@echo "... src/output/xmlLog.s"
	@echo "... src/serialization/ackowledge.o"
	@echo "... src/serialization/ackowledge.i"
	@echo "... src/serialization/ackowledge.s"
	@echo "... src/serialization/airDisplayOpt.o"
	@echo "... src/serialization/airDisplayOpt.i"
	@echo "... src/serialization/airDisplayOpt.s"
	@echo "... src/serialization/airList.o"
	@echo "... src/serialization/airList.i"
	@echo "... src/serialization/airList.s"
	@echo "... src/serialization/damage.o"
	@echo "... src/serialization/damage.i"
	@echo "... src/serialization/damage.s"
	@echo "... src/serialization/endianess.o"
	@echo "... src/serialization/endianess.i"
	@echo "... src/serialization/endianess.s"
	@echo "... src/serialization/flight.o"
	@echo "... src/serialization/flight.i"
	@echo "... src/serialization/flight.s"
	@echo "... src/serialization/ground.o"
	@echo "... src/serialization/ground.i"
	@echo "... src/serialization/ground.s"
	@echo "... src/serialization/header.o"
	@echo "... src/serialization/header.i"
	@echo "... src/serialization/header.s"
	@echo "... src/serialization/includeAll.o"
	@echo "... src/serialization/includeAll.i"
	@echo "... src/serialization/includeAll.s"
	@echo "... src/serialization/int.o"
	@echo "... src/serialization/int.i"
	@echo "... src/serialization/int.s"
	@echo "... src/serialization/left.o"
	@echo "... src/serialization/left.i"
	@echo "... src/serialization/left.s"
	@echo "... src/serialization/login.o"
	@echo "... src/serialization/login.i"
	@echo "... src/serialization/login.s"
	@echo "... src/serialization/map.o"
	@echo "... src/serialization/map.i"
	@echo "... src/serialization/map.s"
	@echo "... src/serialization/message.o"
	@echo "... src/serialization/message.i"
	@echo "... src/serialization/message.s"
	@echo "... src/serialization/missileOpt.o"
	@echo "... src/serialization/missileOpt.i"
	@echo "... src/serialization/missileOpt.s"
	@echo "... src/serialization/unpack.o"
	@echo "... src/serialization/unpack.i"
	@echo "... src/serialization/unpack.s"
	@echo "... src/serialization/userlist.o"
	@echo "... src/serialization/userlist.i"
	@echo "... src/serialization/userlist.s"
	@echo "... src/serialization/weather.o"
	@echo "... src/serialization/weather.i"
	@echo "... src/serialization/weather.s"
	@echo "... src/sockets/linux.o"
	@echo "... src/sockets/linux.i"
	@echo "... src/sockets/linux.s"
	@echo "... src/sockets/socketYS.o"
	@echo "... src/sockets/socketYS.i"
	@echo "... src/sockets/socketYS.s"
	@echo "... src/sockets/windows.o"
	@echo "... src/sockets/windows.i"
	@echo "... src/sockets/windows.s"
	@echo "... src/stringarray.o"
	@echo "... src/stringarray.i"
	@echo "... src/stringarray.s"
	@echo "... src/test.o"
	@echo "... src/test.i"
	@echo "... src/test.s"
	@echo "... src/tests.o"
	@echo "... src/tests.i"
	@echo "... src/tests.s"
	@echo "... src/types/stringarray.o"
	@echo "... src/types/stringarray.i"
	@echo "... src/types/stringarray.s"
	@echo "... src/types/ys/airList.o"
	@echo "... src/types/ys/airList.i"
	@echo "... src/types/ys/airList.s"
	@echo "... src/types/ys/includeAll.o"
	@echo "... src/types/ys/includeAll.i"
	@echo "... src/types/ys/includeAll.s"
	@echo "... src/types/ys/login.o"
	@echo "... src/types/ys/login.i"
	@echo "... src/types/ys/login.s"
	@echo "... src/types/ys/map.o"
	@echo "... src/types/ys/map.i"
	@echo "... src/types/ys/map.s"
	@echo "... src/types/ys/missileOpt.o"
	@echo "... src/types/ys/missileOpt.i"
	@echo "... src/types/ys/missileOpt.s"
	@echo "... src/types/ys/tacknowledge.o"
	@echo "... src/types/ys/tacknowledge.i"
	@echo "... src/types/ys/tacknowledge.s"
	@echo "... src/types/ys/tairDisplayOpt.o"
	@echo "... src/types/ys/tairDisplayOpt.i"
	@echo "... src/types/ys/tairDisplayOpt.s"
	@echo "... src/types/ys/tairList.o"
	@echo "... src/types/ys/tairList.i"
	@echo "... src/types/ys/tairList.s"
	@echo "... src/types/ys/tdamage.o"
	@echo "... src/types/ys/tdamage.i"
	@echo "... src/types/ys/tdamage.s"
	@echo "... src/types/ys/tflight.o"
	@echo "... src/types/ys/tflight.i"
	@echo "... src/types/ys/tflight.s"
	@echo "... src/types/ys/tgound.o"
	@echo "... src/types/ys/tgound.i"
	@echo "... src/types/ys/tgound.s"
	@echo "... src/types/ys/tground.o"
	@echo "... src/types/ys/tground.i"
	@echo "... src/types/ys/tground.s"
	@echo "... src/types/ys/theader.o"
	@echo "... src/types/ys/theader.i"
	@echo "... src/types/ys/theader.s"
	@echo "... src/types/ys/tint.o"
	@echo "... src/types/ys/tint.i"
	@echo "... src/types/ys/tint.s"
	@echo "... src/types/ys/tleft.o"
	@echo "... src/types/ys/tleft.i"
	@echo "... src/types/ys/tleft.s"
	@echo "... src/types/ys/tlogin.o"
	@echo "... src/types/ys/tlogin.i"
	@echo "... src/types/ys/tlogin.s"
	@echo "... src/types/ys/tmap.o"
	@echo "... src/types/ys/tmap.i"
	@echo "... src/types/ys/tmap.s"
	@echo "... src/types/ys/tmessage.o"
	@echo "... src/types/ys/tmessage.i"
	@echo "... src/types/ys/tmessage.s"
	@echo "... src/types/ys/tmissileOpt.o"
	@echo "... src/types/ys/tmissileOpt.i"
	@echo "... src/types/ys/tmissileOpt.s"
	@echo "... src/types/ys/tuserlist.o"
	@echo "... src/types/ys/tuserlist.i"
	@echo "... src/types/ys/tuserlist.s"
	@echo "... src/types/ys/tweather.o"
	@echo "... src/types/ys/tweather.i"
	@echo "... src/types/ys/tweather.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

